### ISSUE TITLE
Chybí závislosti

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/fks-build-tools#1]
Zatím bylo zjištěno, že chybí závislosti na 

- imagemagic (konverze do png)
- inkscape (konverze do a z svg)
- ipe Mirek kompatibilní verze ... Lze přeložit .deb balíček ze zdrojáků lokálně, ?? dát do packages.fykos.cz ??
- texlive-font-utils (epstopdf)

**Comment by Werkov** [comment]
> - imagemagic (konverze do png)

Done.

> - inkscape (konverze do a z svg)

Put into `Recommends` (due to dependencies and their size).

> - ipe Mirek kompatibilní verze ... Lze přeložit .deb balíček ze zdrojáků lokálně, ?? dát do packages.fykos.cz ??

This is a separate issue. My opinion -- I don't want to maintain a new (partial) distribution (I don't think this is a slippery slope argument). My suggestion -- specify what IPE format we want to support (mainly given by SW present in Debian) and push those won't comply :-)

> - texlive-font-utils (epstopdf)

Done.

New package (and dependencies) installed on Astrid:
> ii  fks-buildtools                                                 1.0-7-gef16725
